/**
 * THE NAME-CLAIM CARD, split at the seam where behaviour actually starts.
 *
 * The card is one form with one field in it, and almost none of it is the
 * field: an eyebrow, a headline, a sentence, four benefit bullets, a price
 * block and an early-adopter footer bar are all facts of the build. They
 * render here as ViewDefs, at build, and the component places three strings
 * around the one row that a reader can type into.
 *
 * WHY THE FIELD IS NOT HERE, measured rather than assumed. An island would
 * need three things this engine does not offer:
 *
 *   - The submit button is disabled until the typed name yields a usable slug,
 *     and the slug is `toLowerCase`, a character filter and a truncation of
 *     what was typed. Expressions in a view are PATH LOOKUPS — `$open`,
 *     `$props.label` — with no negation and no string transforms, so neither
 *     the slug nor its emptiness can be written in a view.
 *   - Tracking the field in island state re-renders the island on every
 *     keystroke, and `Island` restores focus by path but NOT the selection
 *     range (only `VibeEngine` captures `selectionStart`/`selectionEnd`). The
 *     caret would jump to the end of the site's single most important input on
 *     every character.
 *   - Dropping the state to avoid that drops the `disabled` attribute with it.
 *     A CSS stand-in (`:has(input:placeholder-shown)`) dims the button without
 *     disabling it, so it stays focusable and still announces as available —
 *     an accessibility regression traded for a smaller diff.
 *
 * So the chrome is configuration and the field is code, which is the honest
 * line. When a view can express a derived value, the whole card follows.
 *
 * THE EYEBROW AND THE HEADLINE STAY IN THE TEMPLATE, and not by taste. The
 * utility layer is generated by scanning the source: a class written in a
 * `class=` attribute is CERTAIN, a class that merely looks like one inside a
 * `.ts` file is a CANDIDATE, and `generate()` emits certain rules first and
 * candidate rules after — after the certain MEDIA BLOCKS included. So a base
 * utility that leaves the last `class=` attribute on the site starts winning
 * over its own `sm:` variant, everywhere, silently.
 *
 * This card held the last class attribute carrying the 2xl text size anywhere
 * in the app. Moving the headline here dropped it into the candidate tier, and
 * its rule (font-size 1.5rem, line-height 1.33333) began overriding the sm
 * variant of the 3xl size (1.875rem, line-height 1.2) — which is still
 * certain, from `Widerruf.svelte`. Measured on two builds made back to back:
 * at 700px the headline rendered 24px where it had rendered 30px, and the
 * whole card grew 3.2px. That is not local to this card either — every
 * heading on the site pairing those two sizes would have flipped.
 *
 * So the headline keeps its class attribute until the pipeline stops letting
 * file type decide cascade order. Everything with no such pairing moves.
 *
 * THE INLINE VARIANT IS GONE. Every one of the five surfaces that mounts this
 * card asks for the banner, and the inline variant was not merely unused: its
 * footer bar cancelled the BANNER padding with negative margins (`-mx-5 -mb-9
 * sm:-mx-10 sm:-mb-11`) while the inline box is padded `px-5 py-7 sm:px-8
 * sm:py-8`, so the bar never lined up with the box it was clipped to.
 *
 * Prose lives in block comments only — the utility scanner reads line comments
 * and one apostrophe in one swallows the class candidates (see footer.ts).
 */
import type { ViewNode } from '@myavenceo/aven-vibes'
import { type Lang, pick } from '$lib/i18n'
import { common } from '$lib/i18n/common'
import { localizedPlan, priceSuffix } from '$lib/i18n/plans'
import { pricing } from '$lib/i18n/pricing'
import { euro, plan } from '$lib/pricing/plans'
import { renderSection } from '$lib/vibes/render'

/* The narrow no-break space between the amount and its currency, which the
   Svelte template wrote as `&nbsp;`. */
const NBSP = ' '

const BULLET_CLASS = 'mt-1.5 size-1.5 shrink-0 rounded-full bg-accent'

function bullet(text: string, weight: 'semibold' | 'medium'): ViewNode {
	return {
		tag: 'li',
		class: 'flex gap-2',
		children: [
			{ tag: 'span', class: BULLET_CLASS, attrs: { 'aria-hidden': 'true' } },
			{ tag: 'span', class: `font-${weight} text-foreground-soft`, text }
		]
	}
}

/**
 * The sentence with its emphasis, and what the price buys.
 *
 * The eyebrow and the headline are NOT here, and the reason is a property of
 * the utility pipeline rather than of this card — see the header.
 */
function bodyView(lang: Lang): ViewNode {
	const t = pick(common, lang).idCta
	const tp = pick(pricing, lang)
	const avenId = plan('aven-name')
	const features = localizedPlan(avenId, lang).features

	const bullets: ViewNode[] = []
	/* The MIND-credit line leads the list because it is the one thing in the
	   box that is not a feature of the name itself. */
	if (avenId.runtime) bullets.push(bullet(tp.mindOnce(avenId.runtime.mindCredits), 'semibold'))
	for (const feature of features) bullets.push(bullet(feature.title, 'medium'))

	return {
		tag: 'div',
		children: [
			{
				/* Our own static copy with inline emphasis, so it goes through the
				   render seam rather than through a text node that would escape it. */
				tag: 'p',
				class:
					'mt-3 text-[length:var(--fs-section)] leading-snug text-foreground-quiet sm:text-[length:var(--fs-title)] mx-auto max-w-2xl',
				text: '@@id-cta-body@@'
			},
			{
				/* Sized and styled exactly like the included-features bullets of avenCEO:
				   a small accent dot and the title, no sub-copy. */
				tag: 'ul',
				class:
					'mt-7 grid gap-x-8 gap-y-2 text-left text-[length:var(--fs-body)] leading-snug text-foreground-soft sm:grid-cols-2',
				children: bullets
			}
		]
	}
}

/** The price, as prominently as avenCEO states its own. */
function priceView(lang: Lang): ViewNode {
	const avenId = plan('aven-name')
	return {
		tag: 'div',
		class: 'rounded-lg border border-border/25 bg-surface-card px-5 py-4 text-center',
		children: [
			{
				tag: 'p',
				attrs: { id: 'id-price-figures' },
				children: [
					/*
					 * The list price, struck, BEFORE the one you pay. An offer that
					 * only shows the discounted number is not an offer, it is a price
					 * — the saving has to be visible or there is nothing to decide.
					 * Rendered only when the plan carries a `listEurPrice`, so it
					 * disappears with the offer instead of having to be remembered.
					 */
					...(avenId.listEurPrice
						? [
								{
									tag: 'span',
									attrs: { id: 'id-price-was' },
									text: `${euro(avenId.listEurPrice)}${NBSP}€`
								} satisfies ViewNode
							]
						: []),
					{
						tag: 'span',
						class: 'text-3xl font-semibold tabular-nums tracking-tight text-foreground',
						text: `${euro(avenId.eurPrice)}${NBSP}€`
					},
					{
						/* Its own row under the figures. On the baseline beside them it
						   read as part of the amount and took width from it; below, the
						   price is the price and the terms annotate it. */
						tag: 'span',
						attrs: { id: 'id-price-terms' },
						text: priceSuffix(avenId, lang)
					}
				]
			}
		]
	}
}

/**
 * The early-adopter perk, as a full-width bar clipped to the rounded
 * corners: negative margins cancel the card padding and the form
 * `overflow-hidden` rounds it off.
 */
function betaView(lang: Lang): ViewNode | null {
	const t = pick(common, lang).idCta
	const ceoBeta = plan('aven-ceo').beta
	if (!ceoBeta) return null
	return {
		tag: 'div',
		class:
			'-mx-5 -mb-9 mt-8 bg-accent px-5 py-4 text-center text-accent-foreground sm:-mx-10 sm:-mb-11 sm:px-10',
		children: [
			{
				tag: 'p',
				class: 'font-bold leading-snug',
				text: t.betaLine(ceoBeta.discountPct, ceoBeta.months)
			},
		]
	}
}

/**
 * The three strings the card places around its heading and its field row.
 * `beta` is empty when no beta is running, which is how the bar disappears
 * without the component knowing what a beta is.
 */
export type IdCtaChrome = { body: string; price: string; beta: string }

const cache = new Map<Lang, Promise<IdCtaChrome>>()

async function render(lang: Lang): Promise<IdCtaChrome> {
	const t = pick(common, lang).idCta
	const beta = betaView(lang)
	return {
		body: await renderSection(bodyView(lang), { '@@id-cta-body@@': t.bodyHtml }),
		price: await renderSection(priceView(lang)),
		beta: beta ? await renderSection(beta) : ''
	}
}

/** Rendered once per language per build — the chrome does not vary by page. */
export function idCtaChrome(lang: Lang): Promise<IdCtaChrome> {
	let chrome = cache.get(lang)
	if (!chrome) {
		chrome = render(lang)
		cache.set(lang, chrome)
	}
	return chrome
}
