/**
 * The generators every surface runs to derive its brand files from `tokens.ts`.
 *
 * These live IN the package rather than in either repo's scripts folder, so the
 * app, the id service and the website all emit their theme from the same code
 * — a consumer cannot accidentally generate a different shape. Each repo keeps
 * only a thin script that calls these and writes the result where it belongs.
 *
 * Output is committed in the consuming repo. That is the whole guarantee: if a
 * hex is edited anywhere but `tokens.ts`, re-running the generator restores it
 * and `git status` is dirty, so drift fails a check instead of shipping.
 */
import {
	COMPONENTS,
	ELEVATION_SCALE,
	INK_SCALE,
	RADIUS_SCALE,
	SCALE_TOKENS,
	SPACE_SCALE,
	TINT_SCALE,
	TRACKING_SCALE,
	TYPE_SCALE
} from './design.js'
import {
	APP_ICON_PLATE,
	APP_ROLES,
	CREAMS,
	FONT_STACK,
	FONT_WEIGHTS,
	RADII,
	ROLES,
	SITE_ROLES,
	SURFACES,
	TONES
} from './tokens.js'

/** Which surface a theme is being generated for. */
export type ThemeVariant = 'app' | 'web' | 'plain'

const BANNER = `/* GENERATED by @myavenceo/aven-ceo — do not edit.
 * Every value here comes from packages/aven-ceo/src/tokens.ts.
 * Re-generate with \`bun run brand:generate\`; edits are overwritten. */`

function block(title: string, entries: Array<[string, string]>): string {
	const body = entries.map(([k, v]) => `\t--color-${k}: ${v};`).join('\n')
	return `\t/* ══ ${title} ══ */\n${body}`
}

/**
 * The Tailwind `@theme` block: tones, creams, surfaces and roles.
 *
 * The `web` variant adds the two roles only the marketing site owns (`accent`,
 * `offer`) and points the font stack at the Google-hosted `Inter` rather than
 * the app's self-hosted `InterVariable`. Everything else is identical by
 * construction — which is what the site's old "copy blocks 1–3 across" comment
 * was asking a human to do by hand.
 */
export function themeCss(variant: ThemeVariant): string {
	const font = variant === 'app' ? FONT_STACK.app : FONT_STACK.web
	const roles = variant === 'web' ? { ...ROLES, ...SITE_ROLES } : { ...ROLES, ...APP_ROLES }
	// `plain` is for a surface with no Tailwind: same tokens, but `:root` rather
	// than `@theme`, since there is no utility generator to feed. The id service
	// is the one of these — it hand-maintained its own copy of the palette until
	// now, under a third set of names, and the copy had gone stale.
	const open = variant === 'plain' ? ':root {' : '@theme {'

	const parts = [
		BANNER,
		'',
		open,
		'\t/* Inter is the single typeface — body, UI, titles, eyebrows. The four',
		'\t * family tokens stay SEPARATE so a dedicated display, serif or mono face',
		'\t * can be brought back by editing one line, with no component changes. */',
		`\t--font-sans: ${font};`,
		`\t--font-display: ${font};`,
		`\t--font-serif: ${font};`,
		`\t--font-mono: ${font};`,
		'',
		...Object.entries(FONT_WEIGHTS).map(([k, v]) => `\t--${k}: ${v};`),
		'',
		block('1 · THE BRAND TONES — the paint, each spelled exactly once', Object.entries(TONES)),
		'',
		block('the cream family, lightest to warmest', Object.entries(CREAMS)),
		'',
		block('2 · THE SURFACES — which rung each part stands on', Object.entries(SURFACES)),
		`\t--color-background: var(--color-surface-cream);`,
		'',
		block('3 · THE ROLES — what a colour MEANS', Object.entries(roles)),
		'',
		...Object.entries(RADII).map(([k, v]) => `\t--${k}: ${v};`),
		...(variant === 'plain' ? [] : ['}', '']),
		// In the plain variant these lines sit INSIDE the single `:root` block,
		// so they carry its indentation; everywhere else they open a new one.
		...[
			'/* ══ 4 · THE SCALES — type, tracking, emphasis, elevation, geometry ══',
			' * A value that is not on a scale is not available. Before these, one',
			' * idiom was written fourteen ways and the type ramp was thirty arbitrary',
			' * sizes mixing px and rem by eye.',
			' *',
			' * Deliberately in `:root` and NOT in `@theme`. Tailwind v4 tree-shakes',
			' * `@theme` variables it sees no utility for, which silently dropped half',
			' * of these — a scale that only exists once something already uses it is',
			' * not a scale, and the next author reaching for `var(--fs-body)` would',
			' * have got nothing. Colours stay in `@theme` above so Tailwind can still',
			' * generate `bg-primary` and friends. */'
		].map((line) => (variant === 'plain' ? `\t${line}` : line)),
		...(variant === 'plain' ? [] : [':root {']),
		...Object.entries(SCALE_TOKENS).map(([k, v]) => `\t--${k}: ${v};`),
		'}',
		''
	]
	return parts.join('\n')
}

/**
 * The shared components as real CSS classes.
 *
 * aven-ui applies `COMPONENTS` directly as a `StyleDef`; the Tailwind surfaces
 * cannot, so they get the same definitions emitted here as an `@layer
 * components` stylesheet. One definition, two delivery mechanisms — which is
 * the only way a card can be guaranteed to look the same in the app, the id
 * service and the website.
 */
export function componentCss(): string {
	const rule = (name: string, decls: Record<string, unknown>): string => {
		const body = Object.entries(decls)
			.map(([prop, value]) => {
				const kebab = prop.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)
				return `\t\t${kebab}: ${String(value)};`
			})
			.join('\n')
		return `\t.${name} {\n${body}\n\t}`
	}
	return [
		BANNER,
		'',
		'@layer components {',
		Object.entries(COMPONENTS)
			.map(([name, decls]) => rule(name, decls))
			.join('\n\n'),
		'}',
		''
	].join('\n')
}

/**
 * THE KITCHEN SINK — every scale and every component, as one static page.
 *
 * Generated from the definitions rather than written by hand, which is the
 * whole point: a hand-maintained showcase drifts from the thing it documents,
 * and this one cannot. Add a component and it appears here; change a step and
 * the swatch moves.
 *
 * It is a plain file with no framework and no build step. Open it in a browser.
 * It lived briefly as a route inside the id service, which meant the design
 * system could only be seen by running a service that consumes it — backwards
 * for something that belongs to the package.
 */
export function kitchenSinkHtml(): string {
	const swatches = (entries: Array<[string, string]>, bordered = false): string =>
		entries
			.map(
				([name, hex]) =>
					`<figure><span class="sw${bordered ? ' sw-b' : ''}" style="background:${hex}"></span><figcaption>${name}<em>${hex}</em></figcaption></figure>`
			)
			.join('')

	const rows = (entries: Array<[string, string]>, style: (t: string) => string): string =>
		entries
			.map(
				([name, value]) =>
					`<p class="row" style="${style(name)}"><span>The quick brown fox</span><em>${name} · ${value}</em></p>`
			)
			.join('')

	return `<!doctype html>
<meta charset="utf-8">
<title>Kitchen sink — @myavenceo/aven-ceo</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300..800&display=swap" rel="stylesheet">
<style>
${themeCss('plain')}
${componentCss()
	.replace('@layer components {', '')
	.replace(/\}\s*$/, '')}
body { font-family: var(--font-sans); background: var(--color-linen); color: var(--color-ink); margin: 0; }
main { max-width: 60rem; margin: 0 auto; padding: 3rem 1.5rem 6rem; }
h1 { font-size: var(--fs-display); margin: .25rem 0 .5rem; letter-spacing: var(--tracking-tight); }
section { margin-bottom: 3rem; }
.sw { display: block; height: 3rem; border-radius: var(--radius-inner); }
.sw-b { border: 1px solid var(--color-border); }
.swatches { display: flex; flex-wrap: wrap; gap: .75rem; margin: .5rem 0 1.5rem; }
figure { margin: 0; width: 6.5rem; }
figcaption { font-size: var(--fs-micro); margin-top: .35rem; display: flex; flex-direction: column; }
em { font-style: normal; color: color-mix(in srgb, var(--color-ink) 50%, transparent); font-size: var(--fs-micro); }
.row { display: flex; align-items: baseline; justify-content: space-between; gap: 1rem; margin: .4rem 0; border-bottom: 1px solid color-mix(in srgb, var(--color-ink) 8%, transparent); padding-bottom: .4rem; }
.grid { display: flex; flex-wrap: wrap; gap: 1rem; }
.box { background: var(--color-porcelain); border: 1px solid var(--color-border); border-radius: var(--radius-inner); padding: 1.25rem; font-size: var(--fs-micro); min-width: 8rem; }
.names { display: flex; flex-wrap: wrap; gap: .35rem; }
.names code { font-size: var(--fs-micro); background: var(--color-surface-soft); padding: .15rem .4rem; border-radius: var(--radius-chip); }
</style>
<main>
<header>
  <p class="eyebrow">@myavenceo/aven-ceo</p>
  <h1>Kitchen sink</h1>
  <p>Generated from the design definitions. ${Object.keys(TONES).length + Object.keys(CREAMS).length} colours ·
     ${Object.keys(TYPE_SCALE).length} type steps · ${Object.keys(COMPONENTS).length} components.</p>
</header>

<section><p class="eyebrow">Colour · tones</p><div class="swatches">${swatches(Object.entries(TONES))}</div>
<p class="eyebrow">Colour · creams</p><div class="swatches">${swatches(Object.entries(CREAMS), true)}</div></section>

<section><p class="eyebrow">Type · ${Object.keys(TYPE_SCALE).length} steps</p>
${rows(Object.entries(TYPE_SCALE), (n) => `font-size:var(--${n})`)}</section>

<section><p class="eyebrow">Tracking · ${Object.keys(TRACKING_SCALE).length} steps</p>
${rows(Object.entries(TRACKING_SCALE), (n) => `letter-spacing:var(--${n});text-transform:uppercase`)}</section>

<section><p class="eyebrow">Ink · text emphasis</p>
${rows(Object.entries(INK_SCALE), (n) => `color:color-mix(in srgb, var(--color-ink) calc(var(--${n}) * 100%), transparent)`)}
<p class="eyebrow">Tint · surfaces, not text</p>
${Object.entries(TINT_SCALE)
	.map(
		([n, v]) =>
			`<div style="background:color-mix(in srgb, var(--color-ink) calc(var(--${n}) * 100%), transparent);padding:.75rem;border-radius:var(--radius-chip);margin:.35rem 0"><em>${n} · ${v}</em></div>`
	)
	.join('')}</section>

<section><p class="eyebrow">Elevation</p><div class="grid">
${Object.keys(ELEVATION_SCALE)
	.map((n) => `<div class="box" style="box-shadow:var(--${n})">${n}</div>`)
	.join('')}
</div></section>

<section><p class="eyebrow">Radius</p><div class="grid">
${Object.entries(RADIUS_SCALE)
	.map(([n, v]) => `<div class="box" style="border-radius:var(--${n})">${n}<br><em>${v}</em></div>`)
	.join('')}
</div>
<p class="eyebrow" style="margin-top:1.5rem">Space</p>
${Object.entries(SPACE_SCALE)
	.map(
		([n, v]) =>
			`<div style="display:flex;align-items:center;gap:.75rem;margin:.4rem 0"><span style="display:block;height:1rem;width:var(--${n});background:var(--color-anchor);border-radius:2px"></span><em>${n} · ${v}</em></div>`
	)
	.join('')}
</section>

<section><p class="eyebrow">Components · ${Object.keys(COMPONENTS).length}</p>
<div class="names">${Object.keys(COMPONENTS)
		.map((n) => `<code>.${n}</code>`)
		.join('')}</div>

<div class="panel stack" style="margin-top:1.5rem">
  <p class="eyebrow">The page card</p>
  <h2 style="margin:0;font-size:var(--fs-lead)">panel + stack</h2>
  <p class="meta">The id service's sheet, promoted. Sign-in, passkey and purchase are all this.</p>
  <div class="well" style="width:100%">
    <p class="eyebrow">well + eyebrow + digits</p>
    <p class="digits">samuel.aven</p>
  </div>
  <div class="steps"><span class="step step-done"></span><span class="step"></span></div>
  <div class="alert">alert — something went wrong, said in the failure tone.</div>
  <p><button type="button" class="btn">btn</button> <button type="button" class="btn-secondary">btn-secondary</button> <button type="button" class="ghost">ghost</button> <span class="chip">chip</span></p>
</div>

<div class="card" style="margin-top:1rem">
  <p class="eyebrow-accent">eyebrow-accent</p>
  <p class="eyebrow-quiet">eyebrow-quiet</p>
  <p>card — the general raised panel.</p>
  <p class="mono-meta">mono-meta · 7eafc029-bf23-419c</p>
  <p style="display:flex;gap:.5rem;align-items:flex-start"><span class="bullet"></span><span>bullet — the dot that opens a list item.</span></p>
</div>
<div class="card-sm" style="margin-top:1rem">card-sm</div>
</section>
</main>
`
}

/* ══ ICONS ═════════════════════════════════════════════════════════════════
 * Two primitives, both derived from ONE file: `assets/logo.svg`.
 *
 *   logo.svg ─┬─→ favicon.svg    the clean mark, squared
 *             └─→ app-icon.svg   the same mark on a rounded brand plate
 *
 * The app icon used to be a hand-kept second copy of the logo's fourteen paths,
 * pre-translated into an 800×800 frame. Editing the logo left it silently
 * stale. Composing with a `<g transform>` instead means the paths exist once. */

/** The square frame both derived icons are drawn in. */
const FRAME = 800
/** The logo's own intrinsic box, read from its `viewBox`. */
const LOGO_W = 486
const LOGO_H = 450

/** Strip the outer `<svg …>` wrapper, keeping just the drawable children. */
function logoBody(logoSvg: string): string {
	const opened = logoSvg.indexOf('>', logoSvg.indexOf('<svg'))
	const closed = logoSvg.lastIndexOf('</svg>')
	if (opened === -1 || closed === -1) throw new Error('logo.svg is not a well-formed <svg>')
	return logoSvg.slice(opened + 1, closed).trim()
}

/** Centre the logo in the square frame — the offsets the old copy hard-coded. */
function centred(logoSvg: string): string {
	const dx = (FRAME - LOGO_W) / 2
	const dy = (FRAME - LOGO_H) / 2
	return `\t<g transform="translate(${dx}, ${dy})">\n\t\t${logoBody(logoSvg)}\n\t</g>`
}

/**
 * The app icon: the mark on a rounded plate, filled from a real brand cream.
 * The plate colour used to be `#F8F1E8` — a fifth cream that belonged to no
 * palette; it is `linen` now, like every other page ground.
 */
export function appIconSvg(logoSvg: string): string {
	return [
		`<svg width="${FRAME}" height="${FRAME}" viewBox="0 0 ${FRAME} ${FRAME}" fill="none" xmlns="http://www.w3.org/2000/svg">`,
		`\t<!-- GENERATED from assets/logo.svg by @myavenceo/aven-ceo — do not edit. -->`,
		`\t<rect width="${FRAME}" height="${FRAME}" rx="160" fill="${APP_ICON_PLATE}" />`,
		centred(logoSvg),
		'</svg>',
		''
	].join('\n')
}

/**
 * The favicon: the clean mark, squared, on nothing. Every surface's `favicon.svg`
 * is this file — replacing three different icons, two of which were SvelteKit's
 * default template logo (`#ff3e00`) and one a hand-drawn monogram in colours
 * (`#17251d` on `#f4f1e8`) that appeared in no palette.
 */
export function faviconSvg(logoSvg: string): string {
	return [
		`<svg width="${FRAME}" height="${FRAME}" viewBox="0 0 ${FRAME} ${FRAME}" fill="none" xmlns="http://www.w3.org/2000/svg">`,
		`\t<!-- GENERATED from assets/logo.svg by @myavenceo/aven-ceo — do not edit. -->`,
		`\t<title>aven</title>`,
		centred(logoSvg),
		'</svg>',
		''
	].join('\n')
}

/** Where the palette says the creams sit — re-exported so scripts can assert. */
export { CREAMS, TONES }
