/**
 * The generators every surface runs to derive its brand files from `tokens.ts`.
 *
 * These live IN the package rather than in either repo's scripts folder, so the
 * app, the id service and the website all emit their theme from the same code
 * — a consumer cannot accidentally generate a different shape. Each repo keeps
 * only a thin script that calls these and writes the result where it belongs.
 *
 * Output is committed in the consuming repo. That is the whole guarantee: if a
 * hex is edited anywhere but `tokens.ts`, re-running the generator restores it
 * and `git status` is dirty, so drift fails a check instead of shipping.
 */
import { COMPONENTS, SCALE_TOKENS } from './design.js'
import {
	APP_ICON_PLATE,
	APP_ROLES,
	CREAMS,
	FONT_STACK,
	FONT_WEIGHTS,
	RADII,
	ROLES,
	SITE_ROLES,
	SURFACES,
	TONES
} from './tokens.js'

/** Which surface a theme is being generated for. */
export type ThemeVariant = 'app' | 'web' | 'plain'

const BANNER = `/* GENERATED by @myavenceo/aven-ceo — do not edit.
 * Every value here comes from packages/aven-ceo/src/tokens.ts.
 * Re-generate with \`bun run brand:generate\`; edits are overwritten. */`

function block(title: string, entries: Array<[string, string]>): string {
	const body = entries.map(([k, v]) => `\t--color-${k}: ${v};`).join('\n')
	return `\t/* ══ ${title} ══ */\n${body}`
}

/**
 * The Tailwind `@theme` block: tones, creams, surfaces and roles.
 *
 * The `web` variant adds the two roles only the marketing site owns (`accent`,
 * `offer`) and points the font stack at the Google-hosted `Inter` rather than
 * the app's self-hosted `InterVariable`. Everything else is identical by
 * construction — which is what the site's old "copy blocks 1–3 across" comment
 * was asking a human to do by hand.
 */
export function themeCss(variant: ThemeVariant): string {
	const font = variant === 'app' ? FONT_STACK.app : FONT_STACK.web
	const roles = variant === 'web' ? { ...ROLES, ...SITE_ROLES } : { ...ROLES, ...APP_ROLES }
	// `plain` is for a surface with no Tailwind: same tokens, but `:root` rather
	// than `@theme`, since there is no utility generator to feed. The id service
	// is the one of these — it hand-maintained its own copy of the palette until
	// now, under a third set of names, and the copy had gone stale.
	const open = variant === 'plain' ? ':root {' : '@theme {'

	const parts = [
		BANNER,
		'',
		open,
		'\t/* Inter is the single typeface — body, UI, titles, eyebrows. The four',
		'\t * family tokens stay SEPARATE so a dedicated display, serif or mono face',
		'\t * can be brought back by editing one line, with no component changes. */',
		`\t--font-sans: ${font};`,
		`\t--font-display: ${font};`,
		`\t--font-serif: ${font};`,
		`\t--font-mono: ${font};`,
		'',
		...Object.entries(FONT_WEIGHTS).map(([k, v]) => `\t--${k}: ${v};`),
		'',
		block('1 · THE BRAND TONES — the paint, each spelled exactly once', Object.entries(TONES)),
		'',
		block('the cream family, lightest to warmest', Object.entries(CREAMS)),
		'',
		block('2 · THE SURFACES — which rung each part stands on', Object.entries(SURFACES)),
		`\t--color-background: var(--color-surface-cream);`,
		'',
		block('3 · THE ROLES — what a colour MEANS', Object.entries(roles)),
		'',
		...Object.entries(RADII).map(([k, v]) => `\t--${k}: ${v};`),
		...(variant === 'plain' ? [] : ['}', '']),
		'/* ══ 4 · THE SCALES — type, tracking, emphasis, elevation, geometry ══',
		' * A value that is not on a scale is not available. Before these, one',
		' * idiom was written fourteen ways and the type ramp was thirty arbitrary',
		' * sizes mixing px and rem by eye.',
		' *',
		' * Deliberately in `:root` and NOT in `@theme`. Tailwind v4 tree-shakes',
		' * `@theme` variables it sees no utility for, which silently dropped half',
		' * of these — a scale that only exists once something already uses it is',
		' * not a scale, and the next author reaching for `var(--fs-body)` would',
		' * have got nothing. Colours stay in `@theme` above so Tailwind can still',
		' * generate `bg-primary` and friends. */',
		...(variant === 'plain' ? [] : [':root {']),
		...Object.entries(SCALE_TOKENS).map(([k, v]) => `\t--${k}: ${v};`),
		'}',
		''
	]
	return parts.join('\n')
}

/**
 * The shared components as real CSS classes.
 *
 * aven-ui applies `COMPONENTS` directly as a `StyleDef`; the Tailwind surfaces
 * cannot, so they get the same definitions emitted here as an `@layer
 * components` stylesheet. One definition, two delivery mechanisms — which is
 * the only way a card can be guaranteed to look the same in the app, the id
 * service and the website.
 */
export function componentCss(): string {
	const rule = (name: string, decls: Record<string, unknown>): string => {
		const body = Object.entries(decls)
			.map(([prop, value]) => {
				const kebab = prop.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)
				return `\t\t${kebab}: ${String(value)};`
			})
			.join('\n')
		return `\t.${name} {\n${body}\n\t}`
	}
	return [
		BANNER,
		'',
		'@layer components {',
		Object.entries(COMPONENTS)
			.map(([name, decls]) => rule(name, decls))
			.join('\n\n'),
		'}',
		''
	].join('\n')
}

/* ══ ICONS ═════════════════════════════════════════════════════════════════
 * Two primitives, both derived from ONE file: `assets/logo.svg`.
 *
 *   logo.svg ─┬─→ favicon.svg    the clean mark, squared
 *             └─→ app-icon.svg   the same mark on a rounded brand plate
 *
 * The app icon used to be a hand-kept second copy of the logo's fourteen paths,
 * pre-translated into an 800×800 frame. Editing the logo left it silently
 * stale. Composing with a `<g transform>` instead means the paths exist once. */

/** The square frame both derived icons are drawn in. */
const FRAME = 800
/** The logo's own intrinsic box, read from its `viewBox`. */
const LOGO_W = 486
const LOGO_H = 450

/** Strip the outer `<svg …>` wrapper, keeping just the drawable children. */
function logoBody(logoSvg: string): string {
	const opened = logoSvg.indexOf('>', logoSvg.indexOf('<svg'))
	const closed = logoSvg.lastIndexOf('</svg>')
	if (opened === -1 || closed === -1) throw new Error('logo.svg is not a well-formed <svg>')
	return logoSvg.slice(opened + 1, closed).trim()
}

/** Centre the logo in the square frame — the offsets the old copy hard-coded. */
function centred(logoSvg: string): string {
	const dx = (FRAME - LOGO_W) / 2
	const dy = (FRAME - LOGO_H) / 2
	return `\t<g transform="translate(${dx}, ${dy})">\n\t\t${logoBody(logoSvg)}\n\t</g>`
}

/**
 * The app icon: the mark on a rounded plate, filled from a real brand cream.
 * The plate colour used to be `#F8F1E8` — a fifth cream that belonged to no
 * palette; it is `linen` now, like every other page ground.
 */
export function appIconSvg(logoSvg: string): string {
	return [
		`<svg width="${FRAME}" height="${FRAME}" viewBox="0 0 ${FRAME} ${FRAME}" fill="none" xmlns="http://www.w3.org/2000/svg">`,
		`\t<!-- GENERATED from assets/logo.svg by @myavenceo/aven-ceo — do not edit. -->`,
		`\t<rect width="${FRAME}" height="${FRAME}" rx="160" fill="${APP_ICON_PLATE}" />`,
		centred(logoSvg),
		'</svg>',
		''
	].join('\n')
}

/**
 * The favicon: the clean mark, squared, on nothing. Every surface's `favicon.svg`
 * is this file — replacing three different icons, two of which were SvelteKit's
 * default template logo (`#ff3e00`) and one a hand-drawn monogram in colours
 * (`#17251d` on `#f4f1e8`) that appeared in no palette.
 */
export function faviconSvg(logoSvg: string): string {
	return [
		`<svg width="${FRAME}" height="${FRAME}" viewBox="0 0 ${FRAME} ${FRAME}" fill="none" xmlns="http://www.w3.org/2000/svg">`,
		`\t<!-- GENERATED from assets/logo.svg by @myavenceo/aven-ceo — do not edit. -->`,
		`\t<title>aven</title>`,
		centred(logoSvg),
		'</svg>',
		''
	].join('\n')
}

/** Where the palette says the creams sit — re-exported so scripts can assert. */
export { CREAMS, TONES }
