<script lang="ts">
/**
 * The name-claim card: chrome from configuration, one link in code.
 *
 * The sentence, the four benefit bullets, the price block and the early-adopter
 * footer bar are ViewDefs rendered at build in `$lib/vibes/id-check-cta.ts` and
 * placed here as three strings. What is left is a single call to action and the
 * two lines above it.
 *
 * THE FIELD IS GONE, and with it the only real behaviour this component had.
 * It asked for the name here and handed it to the id service as a query
 * parameter; the service asks for it again on arrival, so the card was
 * collecting something its destination collects anyway — and paying for it with
 * a slug rule, a derived disabled state, a submit handler and a caret that an
 * island could not have restored. One link replaces all of it.
 *
 * That also settles a question the config-only audit left open. This card was
 * the standing example of a surface that could NOT be a ViewDef, for reasons
 * written out in that file: `disabled = !slug` is a negation of a derived
 * value, and view expressions are path lookups with no negation. With no field
 * there is no slug, no negation, and nothing left that a view cannot say.
 *
 * THE HEADLINE KEEPS ITS CLASS ATTRIBUTE. The utility layer is generated by
 * scanning the source, and a class written in a class attribute outranks the
 * same class seen inside a TypeScript file: certain rules are emitted first and
 * candidate rules after — after the certain media blocks included. This card
 * held the last class attribute on the site carrying the 2xl text size, so
 * moving the headline into a ViewDef made that base rule start beating its own
 * sm variant everywhere. Measured on two builds made back to back: at 700px the
 * headline went from 30px to 24px.
 *
 * Note for whoever edits these comments: never write a class name with a
 * LEADING DOT in this file. The generator reads every Svelte file for DECLARED
 * selectors as well as used ones, so a dotted name in prose is read as "already
 * styled elsewhere" and the utility is then never emitted at all. That is not
 * hypothetical — the first draft of this comment did it, and the headline lost
 * its size rule completely.
 */
import { page } from '$app/state'
import { type Lang, pick } from '$lib/i18n'
import { common } from '$lib/i18n/common'
import { idFunnelHref } from '$lib/id-service'
import type { IdCtaChrome } from '$lib/vibes/id-check-cta'

/*
 * `variant` is still accepted because five surfaces pass it. It selects nothing
 * any more: every surface asks for the banner, and the inline variant is gone —
 * its footer bar cancelled the BANNER padding with negative margins, so it
 * never lined up with its own box.
 */
let { lang = 'de' }: { variant?: 'inline' | 'banner'; lang?: Lang } = $props()

const t = $derived(pick(common, lang).idCta)

const chrome: IdCtaChrome = page.data.idCtaChrome
if (!chrome)
	throw new Error('[id-cta] missing idCtaChrome — this route has no server load for it')
</script>

<div
	class="rounded-3xl border-2 border-accent/25 bg-surface-raised px-5 py-9 shadow-[var(--shadow-raised)] sm:px-10 sm:py-11 overflow-hidden text-center"
>
	<p class="text--eyebrow">{t.eyebrow}</p>
	<h3
		class="mt-2 text-2xl font-semibold tracking-tight text-balance text-foreground sm:text-3xl md:text-[length:var(--fs-amount)] mx-auto max-w-xl"
	>
		{t.title}
	</h3>

	{@html chrome.body}

	<!-- The action block: the price as prominently as avenCEO states its own,
	     then one link to the place that takes the name. -->
	<div class="mt-7 space-y-5">
		{@html chrome.price}
		<a href={idFunnelHref('aven-name')} id="id-claim-action" class="btn btn--accent">
			{t.button}
		</a>
	</div>

</div>
