<script lang="ts">
/**
 * The name-claim card: chrome from configuration, field in code.
 *
 * The sentence, the four benefit bullets, the price block and the early-adopter
 * footer bar are ViewDefs rendered at build in `$lib/vibes/id-check-cta.ts` and
 * placed here as three strings. What is left is the form — one field, one
 * button, and the rule that turns what was typed into a name we can hand to the
 * id service — plus the eyebrow and the headline, which stay for a reason that
 * is not taste.
 *
 * THE HEADLINE KEEPS ITS CLASS ATTRIBUTE. The utility layer is generated by
 * scanning the source, and a class written in a class attribute outranks the
 * same class seen inside a TypeScript file: certain rules are emitted first
 * and candidate rules after — after the certain media blocks included. This
 * card held the last class attribute on the site carrying the 2xl text size,
 * so moving the headline into a ViewDef made that base rule start beating its
 * own sm variant everywhere. Measured on two builds made back to back: at
 * 700px the headline went from 30px to 24px. The full account is in the header
 * of `$lib/vibes/id-check-cta.ts`.
 *
 * Note for whoever edits these comments: never write a class name with a
 * LEADING DOT in this file. The generator reads every Svelte file for
 * DECLARED selectors as well as used ones, so a dotted name in prose is read
 * as "already styled elsewhere" and the utility is then never emitted at all.
 * That is not hypothetical — the first draft of this comment did it, and the
 * headline lost its size rule completely.
 *
 * WHY THE FIELD STAYS. An island cannot express this one yet, and the reasons
 * are specific rather than general — they are written out in the header of
 * `$lib/vibes/id-check-cta.ts`. In short: the disabled state is a NEGATION of a derived slug, and the
 * expressions in a view are path lookups with no negation and no string
 * transforms; and putting the field in island state re-renders on every
 * keystroke, where `Island` restores focus by path but not the selection
 * range, so the caret would jump to the end on every character.
 */
import { page } from '$app/state'
import { type Lang, pick } from '$lib/i18n'
import { common } from '$lib/i18n/common'
import { idFunnelHref } from '$lib/id-service'
import type { IdCtaChrome } from '$lib/vibes/id-check-cta'

/*
 * `variant` is still accepted because five surfaces pass it and one of them is
 * off-limits on this branch. It selects nothing any more: every surface asks
 * for the banner, and the inline variant is gone — its footer bar cancelled
 * the BANNER padding with negative margins, so it never lined up with its own
 * box.
 */
let { lang = 'de' }: { variant?: 'inline' | 'banner'; lang?: Lang } = $props()

const t = $derived(pick(common, lang).idCta)

const chrome: IdCtaChrome = page.data.idCtaChrome
if (!chrome)
	throw new Error('[id-cta] missing idCtaChrome — this route has no server load for it')

let name = $state('')

/**
 * What was typed, as a name the id service can take: lower case, only the
 * characters a subdomain allows, no leading or trailing hyphen, and short
 * enough to be one. Empty means there is nothing to claim yet, which is what
 * disables the button.
 */
const slug = $derived(
	name
		.toLowerCase()
		.replace(/[^a-z0-9-]/g, '')
		.replace(/^-+|-+$/g, '')
		.slice(0, 24)
)

function submit(e: SubmitEvent) {
	e.preventDefault()
	if (!slug) return
	window.location.href = idFunnelHref('aven-name', slug)
}
</script>

<form
	onsubmit={submit}
	class="rounded-3xl border-2 border-accent/25 bg-surface-raised px-5 py-9 shadow-[var(--shadow-raised)] sm:px-10 sm:py-11 overflow-hidden text-center"
	aria-label={t.formLabel}
>
	<p class="eyebrow">{t.eyebrow}</p>
	<h3
		class="mt-2 text-2xl font-semibold tracking-tight text-balance text-foreground sm:text-3xl md:text-[length:var(--fs-amount)] mx-auto max-w-xl"
	>
		{t.title}
	</h3>

	{@html chrome.body}

	<!-- The action block, full card width: the €25 price as prominently as
	     avenCEO states its own, then the name check on one line. -->
	<div class="mt-7 space-y-5">
		{@html chrome.price}
		<!-- One field, read as one address: the name types RIGHT-aligned so it
		     sits flush against the fixed ".aven.ceo" suffix — a divided,
		     non-editable segment at the SAME size. Field and button share one
		     height (h-20) so they line up exactly on desktop.

		     `flex-1` is deliberately `sm:` only. This wrapper is `flex-col`
		     until `sm`, and in a column the MAIN axis is vertical — so an
		     unprefixed `flex-1` sets `flex-basis: 0` on the height and the
		     field collapses to its content (40px) no matter what `h-` says.
		     It did exactly that at h-16 before anyone measured it.

		     The field is the action of this card, so it is deliberately the
		     largest control on it: 80px tall against the button's text, and set
		     one step up the ramp from the rest of the block. -->
		<div class="flex flex-col gap-2.5 sm:flex-row sm:items-stretch">
			<label
				class="flex h-20 items-stretch overflow-hidden rounded-full border-2 border-accent/40 bg-surface-page text-left shadow-[var(--shadow-floating)] sm:flex-1"
			>
				<input
					bind:value={name}
					type="text"
					name="aven-name"
					autocomplete="off"
					spellcheck="false"
					placeholder={t.placeholder}
					class="min-w-0 flex-1 bg-transparent pl-7 pr-2 text-right text-[length:var(--fs-amount)] font-medium tracking-tight text-foreground outline-none placeholder:text-foreground-quiet"
				>
				<span
					class="flex shrink-0 select-none items-center border-l border-accent/30 bg-surface-sunken/60 px-6 text-[length:var(--fs-amount)] font-medium text-foreground-quiet"
					>.aven.ceo</span
				>
			</label>
			<button
				type="submit"
				disabled={!slug}
				class="inline-flex h-20 shrink-0 items-center justify-center rounded-full bg-primary px-9 text-[length:var(--fs-lead)] font-semibold text-primary-foreground transition-opacity hover:opacity-90 disabled:pointer-events-none disabled:opacity-40"
			>
				{t.button}
			</button>
		</div>
	</div>

	{@html chrome.beta}
</form>
