<script lang="ts">
/**
 * The name-claim card: chrome from configuration, one link in code.
 *
 * The sentence, the four benefit bullets, the price block and the early-adopter
 * footer bar are ViewDefs rendered at build in `$lib/vibes/id-check-cta.ts` and
 * placed here as three strings. What is left is a single call to action and the
 * two lines above it.
 *
 * THE FIELD IS GONE, and with it the only real behaviour this component had.
 * It asked for the name here and handed it to the id service as a query
 * parameter; the service asks for it again on arrival, so the card was
 * collecting something its destination collects anyway — and paying for it with
 * a slug rule, a derived disabled state, a submit handler and a caret that an
 * island could not have restored. One link replaces all of it.
 *
 * That also settles a question the config-only audit left open. This card was
 * the standing example of a surface that could NOT be a ViewDef, for reasons
 * written out in that file: `disabled = !slug` is a negation of a derived
 * value, and view expressions are path lookups with no negation. With no field
 * there is no slug, no negation, and nothing left that a view cannot say.
 *
 * THE HEADLINE KEEPS ITS CLASS ATTRIBUTE. The utility layer is generated by
 * scanning the source, and a class written in a class attribute outranks the
 * same class seen inside a TypeScript file: certain rules are emitted first and
 * candidate rules after — after the certain media blocks included. This card
 * held the last class attribute on the site carrying the 2xl text size, so
 * moving the headline into a ViewDef made that base rule start beating its own
 * sm variant everywhere. Measured on two builds made back to back: at 700px the
 * headline went from 30px to 24px.
 *
 * Note for whoever edits these comments: never write a class name with a
 * LEADING DOT in this file. The generator reads every Svelte file for DECLARED
 * selectors as well as used ones, so a dotted name in prose is read as "already
 * styled elsewhere" and the utility is then never emitted at all. That is not
 * hypothetical — the first draft of this comment did it, and the headline lost
 * its size rule completely.
 */
import { page } from '$app/state'
import { type Lang, pick } from '$lib/i18n'
import { common } from '$lib/i18n/common'
import { idFunnelHref } from '$lib/id-service'
import type { IdCtaChrome } from '$lib/vibes/id-check-cta'

/*
 * `variant` is still accepted because five surfaces pass it. It selects nothing
 * any more: every surface asks for the banner, and the inline variant is gone —
 * its footer bar cancelled the BANNER padding with negative margins, so it
 * never lined up with its own box.
 */
let { lang = 'de' }: { variant?: 'inline' | 'banner'; lang?: Lang } = $props()

const t = $derived(pick(common, lang).idCta)

const chrome: IdCtaChrome = page.data.idCtaChrome
if (!chrome) throw new Error('[id-cta] missing idCtaChrome — this route has no server load for it')
</script>

<!-- The panel is the `claim-card` unit now — the shell it wore before was the
     same design restated as ~15 utilities (`rounded-3xl border-2 border-accent/25
     bg-surface-raised ...`), two of which (`rounded-3xl` at 24px, the price's
     `text-3xl` at 30px) were not even on the brand's own scale. The unit is the
     single statement of this card; the storybook composite and this page now
     render from the same declarations.

     The h3 KEEPS its class attribute: it is still the site's only certain-tier
     holder of `text-2xl`, and demoting that utility to candidate tier reorders
     it after the certain media blocks (see the header comment). -->
<div class="claim-card">
	<div class="claim-card-body">
		<p class="text--eyebrow claim-card-eyebrow">{t.eyebrow}</p>
		<h3
			class="text-2xl font-semibold tracking-tight text-balance text-foreground sm:text-3xl md:text-[length:var(--fs-amount)] mx-auto max-w-xl"
		>
			{t.title}
		</h3>

		{@html chrome.body}

		{@html chrome.price}
		<!-- The one action on the card; the part stretches its button full width. -->
		<div class="claim-card-action">
			<a href={idFunnelHref('aven-name')} class="btn btn--accent">
				{t.button}
			</a>
		</div>
	</div>
</div>
